### ISSUE TITLE
Add ubjsc to Libraries

### ISSUE THREAD

**Issue by tsieprawski** [rkalla/universal-binary-json#78]
Hi! I am writing to let you know that for some time I've been developing another library for dealing with UBJSON, in C - ubjsc. [1]

I've just found out that in Libraries there is already a library in C (ubj). As far as I see it for 5 minutes, the main differences are... ubjsc is designed as (much more?) object-oriented (and because of that/for now generates much more overhead, but is much more obvious); is transport independent; it is much heavier tested ([2]); clearly is < 1.0 and far from stable; and it is mine. (:

[1] https://bitbucket.org/tsieprawski/ubjsc
[2]
My internal sonarqube instance reports I have ~98% code coverage for >=250 unittests - I hope they are exhaustive. (:

**Comment by rkalla** [comment]
Fixed!
